# Generated by Django 4.1.7 on 2023-04-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("temperature", models.IntegerField()),
                (
                    "weather",
                    models.CharField(
                        choices=[
                            ("Clear", "Clear"),
                            ("Partly-Cloudy", "Partly-Cloudy"),
                            ("Cloudy", "Cloudy"),
                            ("Light-Rain", "Light-Rain"),
                            ("Raining", "Raining"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "trackCondition",
                    models.CharField(
                        choices=[
                            ("Dry", "Dry"),
                            ("Wet-Dry", "Wet-Dry"),
                            ("Wet", "Wet"),
                        ],
                        max_length=7,
                    ),
                ),
                ("humidity", models.IntegerField()),
                ("groundTemperature", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("team", models.CharField(max_length=255)),
                ("bike", models.CharField(max_length=255)),
                ("dateOfBirth", models.DateField()),
                ("placeOfBirth", models.CharField(max_length=255)),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("points", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                ("points", models.IntegerField(editable=False)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="djangogp.race"
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="djangogp.rider"
                    ),
                ),
            ],
        ),
    ]
