# Generated by Django 4.1.7 on 2023-03-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangogp", "0003_rename_wheather_race_weather"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rider",
            old_name="peso",
            new_name="weight",
        ),
    ]
