# Generated by Django 4.1.7 on 2023-04-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("djangogp", "0006_alter_standings_rider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standings",
            name="rider",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="djangogp.rider",
            ),
        ),
    ]
