# Generated by Django 4.1.7 on 2023-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangogp", "0007_alter_standings_rider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="trackCondition",
            field=models.CharField(
                choices=[("D", "Dry"), ("WD", "Wet-Dry"), ("W", "Wet")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="weather",
            field=models.CharField(
                choices=[
                    ("Cr", "Clear"),
                    ("PC", "Partly-Cloudy"),
                    ("Cd", "Cloudy"),
                    ("LR", "Light-Rain"),
                    ("R", "Raining"),
                ],
                max_length=2,
            ),
        ),
    ]
