# Generated by Django 4.1.7 on 2023-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangogp", "0008_alter_race_trackcondition_alter_race_weather"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="trackCondition",
            field=models.CharField(
                choices=[("Dry", "Dry"), ("Wet-Dry", "Wet-Dry"), ("Wet", "Wet")],
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="weather",
            field=models.CharField(
                choices=[
                    ("Clear", "Clear"),
                    ("Partly-Cloudy", "Partly-Cloudy"),
                    ("Cloudy", "Cloudy"),
                    ("Light-Rain", "Light-Rain"),
                    ("Raining", "Raining"),
                ],
                max_length=15,
            ),
        ),
    ]
